In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("car_project_scaled.csv")
df.head()

year  km_driven  fuel  seller_type  transmission  owner  \
0  2014   1.338363     1            1             1      0   
1  2014   0.887411     1            1             1      2   
2  2006   1.241098     3            1             1      4   
3  2010   1.011202     1            1             1      0   
4  2007   0.887411     3            1             1      0   

   mileage(km/ltr/kg)    engine  max_power  seats  selling_price  
0            0.999896 -0.423804  -0.495682    5.0         450000  
1            0.432289  0.079227   0.339607    5.0         370000  
2           -0.431678  0.077215  -0.382499    5.0         158000  
3            0.899435 -0.126009  -0.042951    5.0         225000  
4           -0.833524 -0.323198  -0.093883    5.0         130000

In [25]:
df.columns

Index(['year', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner',
       'mileage(km/ltr/kg)', 'engine', 'max_power', 'seats', 'selling_price'],
      dtype='object')

In [29]:
x = df.iloc[:,:-1]
y = df["selling_price"]

In [49]:
from sklearn.preprocessing import StandardScaler

In [53]:
ss = StandardScaler()
y = ss.fit_transform(y.values.reshape(-1, 1))

array([[-0.2335288 ],
       [-0.33275929],
       [-0.5957201 ],
       ...,
       [-0.31787472],
       [-0.43198978],
       [-0.43198978]])

In [57]:
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [61]:
from sklearn.linear_model import LinearRegression , Lasso , Ridge , ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error , root_mean_squared_error

In [63]:
lr1 = LinearRegression()
lr1.fit(x_train,y_train)
lr1.score(x_train,y_train)*100 , lr1.score(x_test,y_test)*100

(67.68523649602942, 68.6382509473156)

In [65]:
lr2 = Lasso(alpha=0.2)
lr2.fit(x_train,y_train)
lr2.score(x_train,y_train)*100 , lr2.score(x_test,y_test)*100

(57.952474053359005, 58.95240160429087)

In [67]:
lr3 = Ridge(alpha=0.05)
lr3.fit(x_train,y_train)
lr3.score(x_train,y_train)*100 , lr3.score(x_test,y_test)*100

(67.68523646917288, 68.6382943852129)

In [69]:
lr4 = ElasticNet(alpha=0.1)
lr4.fit(x_train,y_train)
lr4.score(x_train,y_train)*100 , lr4.score(x_test,y_test)*100

(63.22257123248258, 64.6135349568009)

In [131]:
dt = DecisionTreeRegressor(max_depth = 30)
dt.fit(x_train,y_train)
dt.score(x_train,y_train)*100 , dt.score(x_test,y_test)*100

(99.96434283040836, 90.89545122342271)

In [73]:
mean_absolute_error(y_test,dt.predict(x_test)) , mean_squared_error(y_test,dt.predict(x_test)) , root_mean_squared_error(y_test,dt.predict(x_test))

(0.10977476012469743, 0.09446506170656864, 0.3073516905868075)

In [75]:
rf = RandomForestRegressor(n_estimators=100)
rf.fit(x_train,y_train)
rf.score(x_train,y_train)*100 , rf.score(x_test,y_test)*100

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


(99.53655985665995, 96.86053534519073)

In [77]:
mean_absolute_error(y_test,rf.predict(x_test)) , mean_squared_error(y_test,rf.predict(x_test)) , root_mean_squared_error(y_test,rf.predict(x_test))

(0.08734299487541466, 0.031661267590316663, 0.17793613345893708)

In [79]:
rf1 = RandomForestRegressor(n_estimators=100,max_depth=20,min_samples_split=5,min_samples_leaf=2,max_features="sqrt")
rf1.fit(x_train,y_train)
rf1.score(x_train,y_train)*100 , rf1.score(x_test,y_test)*100

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


(98.00478167314782, 96.50266323976896)

In [81]:
mean_absolute_error(y_test,rf1.predict(x_test)) , mean_squared_error(y_test,rf1.predict(x_test)) , root_mean_squared_error(y_test,rf1.predict(x_test))

(0.09111618146478048, 0.03527038116180137, 0.18780410315486018)

In [83]:
svr = SVR()
svr.fit(x_train,y_train)
svr.score(x_train,y_train)*100 , svr.score(x_test,y_test)*100

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(-2.5605963065754134, -2.456578459550296)

In [85]:
knn = KNeighborsRegressor(n_neighbors=1,p=1)
knn.fit(x_train,y_train)
knn.score(x_train,y_train)*100 ,knn.score(x_test,y_test)*100

(99.92980571954114, 96.10506602281467)

In [87]:
for i in range(2,10):
    knn1 = KNeighborsRegressor(n_neighbors=i)
    knn1.fit(x_train,y_train)
    print(i , knn1.score(x_train,y_train)*100 , knn1.score(x_test,y_test)*100)

2 98.49038050897371 96.01907615292711
3 97.53723174926418 95.65231978569709
4 96.89651943792063 95.11196401516767
5 96.18466791441907 94.58281796205054
6 95.56061023153842 94.13190445208515
7 95.23692727818397 93.72867105334144
8 94.88630065024175 93.40466887973997
9 94.71852847764059 93.48619656065127


In [89]:
from sklearn.model_selection import cross_val_score,KFold

In [91]:
cvs = cross_val_score(RandomForestRegressor(),x_train,y_train,cv= KFold(n_splits=10))

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,),

In [93]:
cvs.sort()
cvs

array([0.92636067, 0.94115572, 0.95273224, 0.95999166, 0.96774588,
       0.97407512, 0.97480555, 0.9781936 , 0.98047468, 0.98311864])

In [95]:
cross_val_score(RandomForestRegressor(),x_train,y_train,cv=5)

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,),

array([0.94370511, 0.97539931, 0.96771638, 0.96973705, 0.95942225])

In [97]:
from sklearn.ensemble import VotingRegressor

In [99]:
li = [("dt1",DecisionTreeRegressor()),("rf1",RandomForestRegressor()),("knr1",KNeighborsRegressor())]

In [101]:
vr = VotingRegressor(li)
vr.fit(x_train,y_train)

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\ensemble\_voting.py:622: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


VotingRegressor(estimators=[('dt1', DecisionTreeRegressor()),
                            ('rf1', RandomForestRegressor()),
                            ('knr1', KNeighborsRegressor())])

In [103]:
vr.score(x_train,y_train)*100 , vr.score(x_test,y_test)*100

(99.27897494035982, 96.84726517234115)

In [105]:
from sklearn.ensemble import BaggingRegressor

In [107]:
bgr = BaggingRegressor(estimator=RandomForestRegressor(),n_estimators=30)
bgr.fit(x_train,y_train)

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:505: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return column_or_1d(y, warn=True)


BaggingRegressor(estimator=RandomForestRegressor(), n_estimators=30)

In [109]:
bgr.score(x_train,y_train)*100 , bgr.score(x_test,y_test)*100

(98.6129610172899, 96.65216216819468)

In [111]:
x.head()

year  km_driven  fuel  seller_type  transmission  owner  \
0  2014   1.338363     1            1             1      0   
1  2014   0.887411     1            1             1      2   
2  2006   1.241098     3            1             1      4   
3  2010   1.011202     1            1             1      0   
4  2007   0.887411     3            1             1      0   

   mileage(km/ltr/kg)    engine  max_power  seats  
0            0.999896 -0.423804  -0.495682    5.0  
1            0.432289  0.079227   0.339607    5.0  
2           -0.431678  0.077215  -0.382499    5.0  
3            0.899435 -0.126009  -0.042951    5.0  
4           -0.833524 -0.323198  -0.093883    5.0

In [117]:
y

array([[-0.2335288 ],
       [-0.33275929],
       [-0.5957201 ],
       ...,
       [-0.31787472],
       [-0.43198978],
       [-0.43198978]])

In [119]:
rf.predict([[2006,1.241098,3,1,1,4,-0.431678,0.077215,-0.382499,5.0]])

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([-0.59328897])

In [121]:
rf1.predict([[2006,1.241098,3,1,1,4,-0.431678,0.077215,-0.382499,5.0]])

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([-0.58083074])

In [123]:
bgr.predict([[2006,1.241098,3,1,1,4,-0.431678,0.077215,-0.382499,5.0]])

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but BaggingRegressor was fitted with feature names
  warnings.warn(


array([-0.58510018])

In [133]:
knn.predict([[2006,1.241098,3,1,1,4,-0.431678,0.077215,-0.382499,5.0]])  #3

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([[-0.5957201]])

In [135]:
knn.predict([[2014,1.338363,1,1,1,0,0.999896,-0.423804,-0.495682,5.0]])  #1

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([[-0.2335288]])

# KNeighborsRegressor  is giving the perfect predictions so it is my final model

In [ ]:
# Predict on test data
y_pred_scaled = model.predict(X_test)

# Convert predictions back to original scale
y_pred_original = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1))

# Display the predicted price in the original scale
print(y_pred_original[:5])  # First 5 predicted prices in original scale

In [149]:
y_scaled = knn.predict(x_test)

In [151]:
y_original = ss.inverse_transform(y_scaled.reshape(-1, 1))

In [155]:
print(y_original[:5])

[[198000.]
 [800000.]
 [475000.]
 [180000.]
 [380000.]]
